application: my-xmpp
version: 1
runtime: python
api_version: 1

inbound_services:
- warmup
- xmpp_message
- xmpp_subscribe

builtins:
- remote_api: on
- appstats: on
- datastore_admin: on

handlers:

- url: /favicon.ico
  static_files: static/fav.ico
  upload: static/fav.ico

- url: /.*
  script: main.py
